// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH5Y2i6wIi7A_GjVcKF9Xq_92Rd-dPoYg',
    appId: '1:60550859154:web:4c7c884a6e7f3234a2d94b',
    messagingSenderId: '60550859154',
    projectId: 'todo-list-e8f02',
    authDomain: 'todo-list-e8f02.firebaseapp.com',
    storageBucket: 'todo-list-e8f02.firebasestorage.app',
    measurementId: 'G-RXKXTED0T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWsLdzcUN9Upy7JyiDgShDoXFt5LSV76A',
    appId: '1:60550859154:android:eb3df3f5abdbcdaca2d94b',
    messagingSenderId: '60550859154',
    projectId: 'todo-list-e8f02',
    storageBucket: 'todo-list-e8f02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGi8lBk26KuQS3XATiVtCaePjJLKRu6ng',
    appId: '1:60550859154:ios:3bc739599f1d5193a2d94b',
    messagingSenderId: '60550859154',
    projectId: 'todo-list-e8f02',
    storageBucket: 'todo-list-e8f02.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGi8lBk26KuQS3XATiVtCaePjJLKRu6ng',
    appId: '1:60550859154:ios:3bc739599f1d5193a2d94b',
    messagingSenderId: '60550859154',
    projectId: 'todo-list-e8f02',
    storageBucket: 'todo-list-e8f02.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH5Y2i6wIi7A_GjVcKF9Xq_92Rd-dPoYg',
    appId: '1:60550859154:web:e57a939e916a71b0a2d94b',
    messagingSenderId: '60550859154',
    projectId: 'todo-list-e8f02',
    authDomain: 'todo-list-e8f02.firebaseapp.com',
    storageBucket: 'todo-list-e8f02.firebasestorage.app',
    measurementId: 'G-1X9G11LSKG',
  );
}
